#!/usr/bin/env python
# print numbered lines as a percentage

import sys

lines = sys.stdin.readlines()
nlines = len(lines)

for i in range(nlines):
    fmt = "{0:>4} {1:>6.2f} {2}"
    print fmt.format(i+1, 100.0*i/nlines, lines[i]),
